version: "3.9"

services:
  # =====================
  # AUTH SERVICE
  # =====================
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "8001:8001"
    depends_on:
      - auth_db

  auth_db:
    image: mysql:8
    container_name: auth_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"

  # =====================
  # COURSE SERVICE
  # =====================
  course_service:
    build: ./course_service
    container_name: course_service
    ports:
      - "8002:8002"
    depends_on:
      - course_db

  course_db:
    image: mysql:8
    container_name: course_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_db
    ports:
      - "3308:3306"

  # =====================
  # USER SERVICE
  # =====================
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8003:8003"
    depends_on:
      - user_db

  user_db:
    image: mysql:8
    container_name: user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3309:3306"

  # =====================
  # GRADING SERVICE
  # =====================
  grading_service:
    build: ./grading_service
    container_name: grading_service
    ports:
      - "8004:8004"
    depends_on:
      - grading_db

  grading_db:
    image: mysql:8
    container_name: grading_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grading_db
    ports:
      - "3310:3306"

  # =====================
  # FORUM SERVICE
  # =====================
  forum_service:
    build: ./forum_service
    container_name: forum_service
    ports:
      - "8005:8005"
    depends_on:
      - forum_db

  forum_db:
    image: mysql:8
    container_name: forum_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum_db
    ports:
      - "3311:3306"

  # =====================
  # NOTIFICATION SERVICE
  # =====================
  notification_service:
    build: ./notification_service
    container_name: notification_service
    ports:
      - "8006:8006"
