services:
  # ========================
  # Auth Service + DB
  # ========================
  auth_service:
    build: ./auth_service
    volumes:
      - ./auth_service:/app
    ports:
      - "8001:8001"
    depends_on:
      - auth_db

  auth_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - auth_data:/var/lib/mysql
      - ./auth_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ========================
  # User Service + DB
  # ========================
  user_service:
    build: ./user_service
    volumes:
      - ./user_service:/app
    ports:
      - "8003:8003"
    depends_on:
      - user_db

  user_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3308:3306"
    volumes:
      - user_data:/var/lib/mysql
      - ./user_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ========================
  # Course Service + DB
  # ========================
  course_service:
    build: ./course_service
    volumes:
      - ./course_service:/app
    ports:
      - "8002:8002"
    depends_on:
      - course_db
    command: uvicorn main:app --host 0.0.0.0 --port 8002

  course_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_db
    ports:
      - "3309:3306"
    volumes:
      - course_data:/var/lib/mysql
      - ./course_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ========================
  # Forum Service + DB
  # ========================
  forum_service:
    build: ./forum_service
    volumes:
      - ./forum_service:/app
    ports:
      - "8005:8005"
    depends_on:
      - forum_db

  forum_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum_db
    ports:
      - "8010:3306"
    volumes:
      - forum_data:/var/lib/mysql
      - ./forum_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ========================
  # Grading Service + DB
  # ========================
  grading_service:
    build: ./grading_service
    volumes:
      - ./grading_service:/app
    ports:
      - "8004:8004"
    depends_on:
      - grading_db

  grading_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grading_db
    ports:
      - "8011:3306"
    volumes:
      - grading_data:/var/lib/mysql
      - ./grading_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ========================
  # Notification Service (no DB for now)
  # ========================
  notification_service:
    build: ./notification_service
    volumes:
      - ./notification_service:/app
    ports:
      - "8006:8006"

  # ========================
  # Frontend (React)
  # ========================
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - course_service
      - user_service
      - auth_service
      - forum_service
      - grading_service
      - notification_service

# ========================
# Named Volumes
# ========================
volumes:
  auth_data:
  user_data:
  course_data:
  forum_data:
  grading_data:
